### ISSUE TITLE
Unable to connect to Hidden SSID WiFi Networks

### ISSUE THREAD

**Issue by Ilikemining1** [RattletraPM/gbaxxdumper#2] opened 2021-05-03 22:47 UTC
gbaxxdumper hangs at Connecting to WiFi AP on an AP that the DS will connect to without an issue if the SSID on the router is set to hidden.

Enabling SSID broadcast seems to make it work.

**Comment by RattletraPM** [comment] 2021-05-05 13:01
Duplicate of issue #1

**Closed as completed by RattletraPM** 2021-05-05 13:01 UTC
